"""
03_validate_cleaned_data.py
Runs a battery of validation checks against the cleaned CSVs and writes a
pass/fail report to reports/validation_report.md. Exits non-zero if any
check fails, so it can be used as a CI gate.
Run from the project root: python src/03_validate_cleaned_data.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
import pandas as pd
from utils import CLEAN_USERS_PATH, CLEAN_POSTS_PATH

checks = []  # (description, passed: bool, detail: str)


def check(desc, passed, detail=""):
    checks.append((desc, bool(passed), detail))


def main():
    users = pd.read_csv(CLEAN_USERS_PATH)
    posts = pd.read_csv(CLEAN_POSTS_PATH, parse_dates=['event_time'])

    # --- Users checks ---
    check("Users: no duplicate user_id", users['user_id'].duplicated().sum() == 0,
          f"{users['user_id'].duplicated().sum()} duplicates found")
    check("Users: no missing values in any column", users.isna().sum().sum() == 0,
          f"{users.isna().sum().sum()} missing cells")
    check("Users: follower_count is non-negative", (users['follower_count'] >= 0).all(),
          f"min={users['follower_count'].min()}")
    check("Users: account_created parses as valid dates",
          pd.to_datetime(users['account_created'], errors='coerce').notna().all(), "")

    # --- Posts checks ---
    check("Posts: no fully duplicated rows", posts.duplicated().sum() == 0,
          f"{posts.duplicated().sum()} duplicate rows")
    check("Posts: post_id is unique", posts['post_id'].duplicated().sum() == 0,
          f"{posts['post_id'].duplicated().sum()} duplicate post_ids")
    check("Posts: every user_id exists in the users table",
          posts['user_id'].isin(users['user_id']).all(),
          f"{(~posts['user_id'].isin(users['user_id'])).sum()} orphan rows")
    check("Posts: likes has no negative values (NaN allowed)",
          (posts['likes'].dropna() >= 0).all(),
          f"{(posts['likes'].dropna() < 0).sum()} negative values remain")
    check("Posts: shares has no missing or negative values",
          posts['shares'].notna().all() and (posts['shares'] >= 0).all(), "")
    check("Posts: comments has no missing or negative values",
          posts['comments'].notna().all() and (posts['comments'] >= 0).all(), "")
    check("Posts: event_time parses for every row (no NaT)",
          posts['event_time'].notna().all(),
          f"{posts['event_time'].isna().sum()} unparsed timestamps")
    check("Posts: platform, when present, is one of the 5 known platforms",
          posts['platform'].dropna().isin(
              ['Facebook', 'Instagram', 'Reddit', 'Twitter', 'YouTube']).all(), "")
    check("Posts: no literal placeholder strings ('nan', 'NULL', 'None', '') remain in "
          "platform/text_content",
          not posts['platform'].astype(str).str.lower().isin(['nan', 'null', 'none', '']).any()
          and not posts['text_content'].astype(str).str.lower().isin(['nan', 'null', 'none', '']).any(),
          "")
    check("Posts: event_time is within the observed campaign window (2024-05-01 to 2025-04-30)",
          (posts['event_time'] >= '2024-05-01').all() and (posts['event_time'] <= '2025-04-30 23:59:59').all(),
          f"range {posts['event_time'].min()} to {posts['event_time'].max()}")

    # cross-table: no post dated before its author's account_created
    merged = posts.merge(users[['user_id', 'account_created']], on='user_id', how='left')
    merged['account_created'] = pd.to_datetime(merged['account_created'])
    before = (merged['event_time'] < merged['account_created']).sum()
    check("Posts: no post is dated before its author's account_created date",
          before == 0, f"{before} rows violate this")

    # --- Write report ---
    lines = ["# DATA VORTEX — Cleaned Data Validation Report\n",
             "Generated by `src/03_validate_cleaned_data.py`.\n",
             f"| # | Check | Result | Detail |",
             f"|---|-------|--------|--------|"]
    all_passed = True
    for i, (desc, passed, detail) in enumerate(checks, 1):
        status = "PASS" if passed else "FAIL"
        if not passed:
            all_passed = False
        lines.append(f"| {i} | {desc} | {status} | {detail} |")
    lines.append(f"\n**Overall: {'ALL CHECKS PASSED' if all_passed else 'SOME CHECKS FAILED'} "
                 f"({sum(p for _, p, _ in checks)}/{len(checks)})**\n")

    os.makedirs("reports", exist_ok=True)
    with open("reports/validation_report.md", "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Validation complete: {sum(p for _, p, _ in checks)}/{len(checks)} checks passed.")
    for desc, passed, detail in checks:
        if not passed:
            print(f"  FAIL: {desc} ({detail})")

    if not all_passed:
        sys.exit(1)


if __name__ == "__main__":
    main()
