"""
Generates notebooks/DataVortex_Analysis.ipynb — a single reproducible
notebook that walks through audit -> clean -> validate -> EDA -> insights,
calling the exact same src/ modules used by the standalone scripts (so the
notebook and the scripts can never drift apart).
"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []


def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))


def code(text):
    cells.append(nbf.v4.new_code_cell(text))


md("""# DATA VORTEX — Rebuilding the Social Engine
### End-to-end audit -> clean -> validate -> EDA -> insights pipeline

This notebook reproduces the full analysis using the shared modules in `src/`.
It reads only from `data/raw/` (never modified) and writes cleaned data to
`data/cleaned/`, figures to `reports/figures/`, and text reports to `reports/`.

Run this notebook from the **project root** (`datavortex/`), or run
`jupyter nbconvert --execute` from the project root as done for this
submission.""")

code("""import sys, os
sys.path.insert(0, os.path.abspath('../src'))
os.chdir('..')  # run from project root so relative paths (data/, reports/) resolve
import pandas as pd
pd.set_option('display.max_columns', None)
print('Working directory:', os.getcwd())""")

md("## 1. Audit the raw data\nQuantifies every data quality issue before touching anything.")
code("""import subprocess
result = subprocess.run(['python3', 'src/01_audit_raw_data.py'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)""")

code("""with open('reports/audit_report.md') as f:
    print(f.read())""")

md("## 2. Clean the data\nDeterministic, documented transformations. Raw files are never modified; "
   "missing data is preserved as missing rather than invented.")
code("""result = subprocess.run(['python3', 'src/02_clean_data.py'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)""")

code("""with open('reports/cleaning_log.md') as f:
    print(f.read())""")

md("## 3. Validate the cleaned data\nA battery of pass/fail checks against the cleaned CSVs.")
code("""result = subprocess.run(['python3', 'src/03_validate_cleaned_data.py'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)
assert result.returncode == 0, "Validation failed — see reports/validation_report.md"
""")

code("""validation = pd.read_csv('reports/validation_report.md', sep='|', skiprows=6, engine='python',
                          names=['_', 'n', 'check', 'result', 'detail', '__'])
validation = validation[['n', 'check', 'result', 'detail']].dropna(subset=['check'])
validation.head(20)""")

md("## 4. Exploratory Data Analysis\nLoad the cleaned data directly and look at shape, types, and summary stats "
   "before regenerating the figures used in the report.")
code("""users = pd.read_csv('data/cleaned/users_cleaned.csv', parse_dates=['account_created'])
posts = pd.read_csv('data/cleaned/posts_cleaned.csv', parse_dates=['event_time'])
print(users.shape, posts.shape)
users.head()""")

code("""posts.head()""")

code("""posts.describe(include='all').T""")

code("""result = subprocess.run(['python3', 'src/04_eda_and_visuals.py'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)""")

md("### Figures\nGenerated into `reports/figures/` by the cell above; displayed inline below.")
code("""from IPython.display import Image, display
import glob
for path in sorted(glob.glob('reports/figures/*.png')):
    print(path)
    display(Image(filename=path))""")

md("## 5. Insights — Rebuilding the Social Engine\nNon-obvious, data-backed findings computed straight from the cleaned data.")
code("""result = subprocess.run(['python3', 'src/05_insights.py'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)""")

code("""with open('reports/insights.md') as f:
    print(f.read())""")

md("## Summary\n\nSee `README.md` for the polished write-up of this project, and "
   "`STATE.md` for the current status of the submission. Every number quoted in the "
   "README traces back to a cell in this notebook or to `reports/*.md`, which are all "
   "regenerated by the `src/*.py` scripts run above.")

nb['cells'] = cells

import os
os.makedirs('notebooks', exist_ok=True)
with open('notebooks/DataVortex_Analysis.ipynb', 'w') as f:
    nbf.write(nb, f)
print("Notebook written to notebooks/DataVortex_Analysis.ipynb")
